apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/dev/cert-manager-config
  prune: true
  wait: true
  timeout: 5m0s